#!/bin/sh

# Install Yay
if ! command -v yay >/dev/null 2>&1; then
    sudo pacman -S --noconfirm --needed git base-devel 
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
fi

yay -S --noconfirm --needed $(< packages.txt)
