#!/bin/sh

set -euo pipefail
if [ "$EUID" -eq 0 ]; then
  echo "Do not run this script as root."
  exit 1
fi

package_list_path=$XDG_CONFIG_HOME/yadm/packages.txt

if [ ! -f "$package_list_path" ]; then
  echo "$package_list_path not found"
  exit 1
fi

flatpak_list_path=$XDG_CONFIG_HOME/yadm/flatpaks.txt

if [ ! -f "$package_list_path" ]; then
  echo "$flatpak_list_path not found"
  exit 1
fi

wallpaper_location=$XDG_PICTURES_DIR/wallpapers
# Ensure that wallpaper is set
if [ ! -f $wallpaper_location/wallpaper ]; then
  echo "setting wallpaper"
  mkdir -p $wallpaper_location
  cp $XDG_CONFIG_HOME/yadm/wallpaper.png $wallpaper_location/wallpaper
fi

sudo pacman -S --noconfirm --needed git base-devel 
# Install Paru
if ! command -v paru >/dev/null 2>&1; then
    echo "Installing Paru AUR helper"
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si
fi

echo "Installing needed packages"
yay -S --noconfirm --needed --quiet $(< $package_list_path) 2>&1 | grep -vi "warning:"

echo "Installing needed flatpaks"
flatpak install -y $(< $flatpak_list_path) 2>&1 | grep -vi "warning:"

echo "Installing nvim plugins"
nvim --headless -c 'Lazy sync' -c 'qa'

echo "Setting groups"

sudo usermod -a -G storage $(whoami)
sudo usermod -a -G scanner $(whoami)
sudo usermod -a -G docker $(whoami)

TARGET_SHELL="/usr/bin/zsh"
CURRENT_SHELL=$(basename "$SHELL")

if [ "$SHELL" != "$TARGET_SHELL" ]; then
  echo "Current shell is $SHELL, changing to $TARGET_SHELL..."
  chsh -s "$TARGET_SHELL"
  echo "Shell changed. Please log out and log back in for changes to take effect."
else
  echo "Shell is already set to $TARGET_SHELL."
fi

git config --global pull.rebase true

gitlab_url="git@gitlab.com:michaelagallo95/dotfiles.git"
github_url="git@github.com:Michael-Gallo/Dotfiles.git"
remote_name="origin"
current_origin_url=$(yadm remote get-url "$remote_name" 2>/dev/null || echo "")

if [ "$current_origin_url" != "$gitlab_url" ]; then
    echo "Setting GitHub/GitLab remote structure"
    yadm remote remove $remote_name 2>/dev/null || true
    yadm remote add $remote_name $gitlab_url
    yadm fetch
    current_branch=$(yadm symbolic-ref --short HEAD)
    yadm branch --set-upstream-to="$remote_name/$current_branch" "$current_branch"
    yadm remote set-url --add --push $remote_name $gitlab_url
    yadm remote set-url --add --push $remote_name $github_url
fi


if ls /sys/class/power_supply/ | grep -q "^BAT"; then
    echo "Setting laptop class"
    yadm config local.class laptop

fi

yadm alt
# Needed for previews
mkdir -p $HOME/.cache/lf/thumbnail

# Write files

write_if_different() {
  local content="$1"
  local target_file="$2"
  local tmp_file="${target_file}.tmp"

  # Write content to a temporary file with sudo
  echo "$content" | sudo tee "$tmp_file" >/dev/null

  # Compare temporary file with target file
  echo "comparing file $target_file to $tmp_file"
  if ! sudo cmp -s "$target_file" "$tmp_file"; then
    # Replace target file only if different
    sudo mv "$tmp_file" "$target_file"
    echo "Updated $target_file"
  else
    # Remove temporary file if no difference
    sudo rm "$tmp_file"
  fi
}

# Disable the annoying pcspkr module/beep sound
write_if_different "blacklist pcspkr"  /etc/modprobe.d/nobeep.conf
write_if_different "[default_session]
command = \"Hyprland\"
user=\"$(whoami)\" " /etc/greetd/tuigreet.toml
# make it take 10 retries to lock me out
write_if_different "$(cat faillock.conf)" /etc/security/faillock.conf



# Enable services
sudo systemctl enable avahi-daemon.service --now
sudo systemctl enable cups.service --now
