TERMINAL=foot
BROWSER=brave
WALLPAPER_DIR=/home/mike/Pictures/wallpapers
CALCULATOR=galculator
CALENDAR=evolution
FILE_MANAGER=pcmanfm
TERMINAL_FILE_BROWSER=lf
EDITOR=nvim
SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/ssh-agent.socket
