#!/bin/sh

url=$1
proton_dir=$HOME/.steam/root/compatibilitytools.d/

if  [[ "$url" == "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/"* ]];
then
        proton_file=$(echo $url|awk -F '/' '{print $NF}')
        mkdir -p $proton_dir
        wget $1
        echo "extracting $proton_file to $proton_dir"
        tar -xf $proton_file -C $proton_dir
        rm $proton_file

else
        echo "NOT A VALID GE RELEASE"
fi



