#!/bin/bash

# shell script to use searx from the command line
special_prefixes=("wp" "ai")
if [[ " ${special_prefixes[*]} " == *" $1 "* ]]; then
        query="%21"
fi
query=$query$1
for term in "${@:2}" ; do
        # echo  "$term"
        query="$query%20$term"
done

firefox "https://searx.ninja/?preferences=eJxtVEGv0zAM_jX0Ug0B78CpBwRCPAnpPbE9rpGXuq1pEpck3VZ-PU7bbemDwzrF-fzZnx1bQ8SWPWGoWnTowRQGXDtCixW63cu-MKzBpEMBY2TNdjAYsapH3adfywVZQavB82WqDn7EwmLsuK6en_aHIkCDAcHrrnpXxA4tVhw0-MJjGE0Mip1yeFYRjtVXMAGLmknJJZsT-ipo2nXj8W08F7PbLsRJsjHckuYaT7safF_UFOBosFboWnKipQHPrNQq6c2Hz0sKyaVMH6UoirVlbg2WJ6qRg1LLv9hBt4FHASVlyeAmAKUaMvMJPZ-pzukTOZ2wpJBbf5_BxdxwYpBzYE1gSos1gRgj9xNHDh334O5BLP9C7HPvnnQPQSLYMZBO6VMrsiHE_6JuakYXBkF1mZ6rwBtmrcQCyIAB_ziwOf_7h4ePl8xzKc01JRj60pL37LcllgSmEoYh3AU2HrEM3MQzeCxr8qgj-2n1azxYMHT0217lmaRb8FOZLGFb-au-a6wJXI2XHIGR2Wx81kzlMYo5fWe_bvuOrsRXvY0n1xPorGTvL9lhfYgrXQeScfqsml61_tZXaXwkOzci5i29ynnl97qLc7Fnsjun1noXTxn2SPEo84txDUIOsls7WbTSjTJ6cMHIlti896XpN3Q91ui21Z0sOyOzmFt5QOdx4EzJJmM-EYZ_ntZSywLddsTvQz-YUUyhehJ6tawVJaH72245yrwG9GnHJNpH15CjiCpoz8bcmK88ezSNEhB7C5HYJZ-Z-5PWKG348vQoYc5eKOTmJ9mdoR5Vx7HHKYG_HQ7P-wxy8CCF9urlx3exikz0Yt3PKynlqJclPKmARoagkPai5PEXh2UdWA==&q=$query"
