#!/bin/sh

# In LARBS, ~/.config/wall.png is the location of the system wallpaper.  This
# script, if given an argument, moves it there.  This script without an
# argument sets ~/.config/wall.png as the wallpaper, which is required on login
# if you don't want a black screen.
#
# You may also give a directory name to select a random image from that
# directory as a wallpaper. Be careful that the directory only has images.
file=~/.config/wall.png
[ -f "$1" ] && file=$1
[ -d "$1" ] && file="$1$(ls $1 | shuf -n 1)"

echo $file
wal -i $file
cp $file ~/.config/wall.png
