hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("foot --server")
    hl.exec_cmd("dunst")
    hl.exec_cmd("swaybg -i $WALLPAPER_DIR/wallpaper")
    hl.exec_cmd("$HOME/.bin/make_bitwarden_float_hyprland.sh")
end)