# vim: set filetype=sh
alias :q=exit
alias r="ranger"
alias sapt="sudo apt"
alias mkd="mkdir -pv"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ii=nemo
alias vim=nvim
alias svim='sudoedit'
alias df='df -h'
alias mkdir="mkdir -pv"
command -v exa >/dev/null && alias ls="exa -a --color=always --group-directories-first --git --icons"
alias lo=libreoffice
alias pm=pcmanfm
alias sdn="shutdown now"
alias nm=neomutt
alias sm=smplayer
alias yp="yadm push -f"
alias ys="yadm status"
alias ya="yadm add"
alias gp="git push -f"
alias gs="git status"
alias pac="sudo pacman"
alias du="du -h"
alias nmap="nmap -sn"
alias hellolight="sudo systemctl start lightdm"
alias goodbyelight="sudo systemctl stop lightdm"
# cwd to copy current directory to clipboard
alias cwd="pwd|xsel -ib"
unalias gc 2>/dev/null
unalias gd  2>/dev/null

se() {
        bad_dirs="chromium bravesoftware cache discord libreoffice skype lutris .git .log mattermost mangagamer smplayer wayofthepassivefist pcsx2 indexeddb unity3d mono.addins rocket.chat virtualbox"
        vals=(${bad_dirs// /\|})
        rg --files --hidden $HOME/.config $HOME/.bin | grep -E -vi $vals| fzf --layout=reverse | xargs -r $EDITOR ;
}

yc() {
        [ -z $1 ] &&  yadm status | grep modified:| awk '{print $2}' |fzf | xargs yadm commit ||yadm commit $@  
        }
yd() {
        yadm status| grep modified:| awk '{print $2}' |fzf |xargs yadm --no-pager diff 
        }
gd() {
        git status| grep modified:| awk '{print $2}' |fzf |xargs git diff 
        }
