# vim: set filetype=sh
alias :q=exit
alias sv="sudo vim"
alias r="ranger"
alias sapt="sudo apt"
alias mkd="mkdir -pv"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ii=nemo
alias vim=nvim
alias svim='sudo -E vim'
alias df='df -h'
alias mkdir="mkdir -pv"
command -v exa >/dev/null && alias ls="exa -al --color=always --group-directories-first"
alias lo=libreoffice
alias pm=pcmanfm
alias sdn="shutdown now"
alias nm=neomutt
alias sm=smplayer
alias yp="yadm push"

se() {
        bad_dirs="chromium bravesoftware cache discord libreoffice skype lutris .git .log mattermost mangagamer smplayer wayofthepassivefist pcsx2 indexeddb unity3d mono.addins rocket.chat virtualbox"
        vals=(${bad_dirs// /\|})
        rg --files $HOME/.config/* $HOME/.bin/* | grep -E -vi $vals| fzf | xargs -r $EDITOR ;
}
yc() {
        yadm status| grep modified:| awk '{print $2}' |fzf |xargs yadm commit 
        }
yd() {
        yadm status| grep modified:| awk '{print $2}' |fzf |xargs yadm diff 
        }
