#!/bin/sh
# Script that sets bemenu opts
option_max=5
width=0.3
height="30"
title="bmenu"
font="monospace [12]"
title_bg="#169f6f"
title_fg="#181717"
normal_bg="#181717" 
normal_fg="#bdbdbd"
highlighted_fg="#181717"
highlighted_bg="#169f6f"
selected_bg="#181717" 
selected_fg="#181717" 
scrollbar_fg="#181717" 
scrollbar_bg="#181717" 
# Filter is the term for the query
filter_bg="#bdbdbd" 
filter_fg="#169f6f" 


export BEMENU_OPTS="--center -W $width --list $option_max -H $height --fn $font --prompt $title -i --tb $title_bg --tf $title_fg \
--nb $normal_bg --nf $normal_fg --hf $highlighted_fg --hb $highlighted_bg\
--sb $selected_bg --sf $selected_fg --scb $scrollbar_bg --scf $scrollbar_fg\
--fb $filter_bg --ff $filter_fg"

